version: '3.5'

services:
  jobstrainer:
    image: ${DOCKER_REGISTRY-}jobstrainer
    build:
      context: .
      dockerfile: JobsTrainer/Dockerfile
    ports:
      - 8082:80
  jobstrainerml.api:
    image: ${DOCKER_REGISTRY-}jobstrainerml
    build:
      context: .
      dockerfile: JobsTrainerML.Api/Dockerfile
    ports:
      - 8083:80 