// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace JobsTrainerML.Model
{
    public class ModelInput
    {
        [ColumnName("JobId"), LoadColumn(0)]
        public float JobId { get; set; }


        [ColumnName("Sample"), LoadColumn(1)]
        public string Sample { get; set; }


        [ColumnName("Sentiment"), LoadColumn(2)]
        public string Sentiment { get; set; }


        [ColumnName("Country"), LoadColumn(3)]
        public string Country { get; set; }


        [ColumnName("Company"), LoadColumn(4)]
        public string Company { get; set; }


        [ColumnName("CreatedAt"), LoadColumn(5)]
        public string CreatedAt { get; set; }


        [ColumnName("IsEasy"), LoadColumn(6)]
        public bool IsEasy { get; set; }


        [ColumnName("Title"), LoadColumn(7)]
        public string Title { get; set; }


        [ColumnName("CompanyLink"), LoadColumn(8)]
        public string CompanyLink { get; set; }


    }
}
